version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    environment:
      - BACKEND_PROTOCOL=http
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENTRY_TTL=500
      - SHORTURL_NOCH=10

  redis:
    image: 'redis:alpine'